---
sources:
  local:
    - playbook.yml

  url:
    #- name: playbook.yml
    #  url: https://db.tt/VcyI9dvr

  git:
    - name: 'osx'
      repo: 'https://github.com/seakayone/ansible-osx'
      playbooks:
         - better-touch-tool.yml
         - chrome-stable.yml
         - dropbox.yml
         - github.yml
         - homebrew.yml
         - iterm2.yml
         - java6.yml
         - libreoffice.yml
         - skype.yml
         - vagrant.yml
         - virtualbox.yml
         - xtra-finder.yml
